Redesign
opencast/opencast-editor pull request #1079
Opened 2023-06-12 06:42 UTC by Arnei

Resolves #1076.

*Currently a draft due to still being worked on.*

Changes the appearance of the editor to bring it more in line with Opencast Studio and Tobira. Focuses on visual changes, functional changes should be minimal.

2023-06-20 16:50 UTC, lkiesow commented
Here are a few initial thoughts. I will also bring this to our requirements management team later this week and bring back the feedback I get from them. And before: The functional I was thinking of in the technical meeting are not part of this. So, no complaints on that :+1: 

I like the new placement of control elements and part of the new scaling: The UI requires scrolling less often. Although, you now have to always scroll in Firefox by a few pixels. But that should be easy to fix.

I dislike the new colors. The new, faded look is strenuous to use. Especially if you have to work with this for a long time. I would really like to see black text. If necessary, we could do some blue accents, but I'm not sure, I would even do that. The reasoning behind that is that keeping this to neutral colors makes the editor fit way better into other tools. And remember, that the editor is a tool often integrated into other tools like an LMS.

![Screenshot from 2023-06-20 18-09-15](https://github.com/opencast/opencast-editor/assets/1008395/11898711-39b9-47e7-bceb-c137c7fd4c99)

Another big argument against the current colors is the contrast. Knowing that I'm a bad (or good) example, I asked a college what he thought about the colors, not telling him any of my thoughts, and he immediately complained about the contrast. a notion I can wholeheartedly support.

![Screenshot from 2023-06-20 17-52-50](https://github.com/opencast/opencast-editor/assets/1008395/658dce60-b819-4ffc-80ff-56dd280c65ae)

Throwing colors like this into a color checker supports this feeling:

![Screenshot from 2023-06-20 18-08-51](https://github.com/opencast/opencast-editor/assets/1008395/12a954ef-4265-4586-9cbb-ae6b247288ed)

The same goes for the dark mode – which also changed. Again, here I would rather like to see a more neutral color scheme like this (I just removed the light blue backgrounds):

![Screenshot from 2023-06-20 18-13-51](https://github.com/opencast/opencast-editor/assets/1008395/27dd3b0d-081e-44cc-8bda-c4158fe6ac20)

Additional minor improvements I see are the unnecessary large back background for the videos, which iirc was already present before but less noticeable and the fact that the video preview now is much smaller while we have a lot of empty space wasted on the top and bottom of the wavefrom area.

2023-06-20 16:57 UTC, lkiesow commented
Forgot one thing: The icons are not properly aligned in the cutting view and the icon weight of some icons is really different

![Screenshot from 2023-06-20 18-09-15](https://github.com/opencast/opencast-editor/assets/1008395/65589119-e96d-4513-a643-2ed275054dd8)

For example, the bold, filled out waste basked is much larger and goes much lower than the small and delicate left and right arrows.

2023-06-21 06:13 UTC, Arnei commented
Thanks for the extensive review!

> Although, you now have to always scroll in Firefox by a few pixels.

What resolution and possibly zoom level are you using?

> The new, faded look is strenuous to use.

Agreed that this will be more strenuous to use for some people. Would upping the contrast (using darker blues on the text/icons) maybe already help? My personal feeling is that switching from greyscale to bluescale still makes for a pretty neutral colorscheme overall. And to get really vague, they make the editor look "softer" and thus look more "approachable" in a way. So I'm not ready to give up on blue just yet.
(...Though I'm still not quite sure what the reasoning was for using mostly blue text but then still black text in some other places (title, metadata fields))

> Again, here I would rather like to see a more neutral color scheme like this (I just removed the light blue backgrounds):

That I can wholeheartedly support. The light blue backgrounds are the ones on the timeline, correct? Or are there more I've missed?

> Additional minor improvements I see are the unnecessary large back background for the videos, which iirc was already present before but less noticeable and the fact that the video preview now is much smaller while we have a lot of empty space wasted on the top and bottom of the wavefrom area.

Videos now have a maxHeight to make room for the bigger Timeline. This means they will now be unable to fill the full width of the editor on most normal resolutions, resulting in black backgrounds. I'm not sure if I
- like the black backgrounds
- should smush the videos together like in the Thumbnail view (which removes the black backgrounds)
- remove the black backgrounds but keep the videos spaced
Also I don't think there is a lot of wasted space at the top and bottom of the waveform area. At least not compared to how it was before. I could try to dynamically calculate the maxHeight of the video area based on the height of all other elements in order to fill more vertical space with video, but that might prove difficult.

2023-06-28 13:29 UTC, lkiesow commented
>> icon weight of some icons is really different
>
> That could probably use some tweaking, true. The problems of switching to a new icon library that has much less icons than the old one. I.e. the scissors and chevrons are feather icons, the trash can is still a fontawesome icon (because feather does not have a "trashRestore" icon).

I remember being in an early meeting with the designer hired by ETH where the lack of certain icons was discussed already. Back then, I was dead set against introducing new icons if they are not part of an easy-to-use icon library. Back then, I was assured that missing icons would be contributed back to the new libraries (I think it was hero Icons and Feather Icons?). That was okay for me. I find it concerning that this doesn't seem to happen now.

If the idea is no longer to contribute the missing icons back upstream, let us please continue to use Font Awesome, where we have all icons we need right now.

2023-06-29 09:43 UTC, lkiesow commented
>    The new, faded look is strenuous to use.
>
>> Agreed that this will be more strenuous to use for some people. Would upping the contrast (using darker blues on the text/icons) maybe already help?

This is not a binary thing and thus not only good or bad but everything in between. Using a darker blue for text and icons and therefor increasing the contrast will surely help. How much depends on the exact colors you are using in the end.

> My personal feeling is that switching from greyscale to bluescale still makes for a pretty neutral colorscheme overall. 

That really depends on where you include this. For example, this should work [for ETH and their color scheme](https://video.ethz.ch/) with no problem. However, thinking for example about the [yellow colors of Uni Graz](https://sprachliche-bildung.uni-graz.at/de/videos/)… well… blue will not complement them nicely.

Once you use colors, they can clash. If you stick to grayscale, it should generally work with anything.

But again, this is not necessarily binary. The more color you use and especially if you use colors for large areas, the more likely it is to become a problem. So, maybe try blue icons and borders to bring some colors to the tool, but prevent it from becoming a completely blue tool. Like, for example, don't use the prominent blue background on the waveform or don't use the blue background on the buttons.

2023-07-03 14:48 UTC, lkiesow commented
> The logo SVG should convert the text node to a path as otherwise it's shown incorrectly on devices without the "Comfortaa" font

That's my mistake. Fixed in pull request #1096

2023-07-03 15:09 UTC, LukasKalbertodt commented
> This might easily cause developers to fall back to throwing in anything.

Yeah, we need to avoid that. I share your concern there.

> that they would be upstreamed before we use them or not being used.

That's not how I remember our discussions, but it was quite a while ago, so I could easily be mistaken. 
But what's the alternative? You say "or not being used", so I assume: completely switch back to font awesome? But that's only a viable solution if we haven't completely switched to feather+hero yet, right? And the problem is that we of course didn't know it advance what kind of icons we'd ever need for our projects. If it was clear from the get go that we'd need to self-made several icons, sure, then we should have decided against feather+hero. Absolutely. But that was not the case and so far we only ever needed to self-made a very small number of icons.

> But this pull request nicely shows that there seems to be many general icons missing

That's not really the impression I'm getting. The direct font awesome dependencies are removed in this PR, meaning that font awesome icons are used through react icons, where they start with `Fa`. So I searched for `<Fa` in the PR diff (with all files expanded) and only found 5 instances. (Let me know if my assumptions here are incorrect; but yes, I think there are only 5 font awesome icons left):
- `<FaTrash />` and `<FaTrashRestore />`: the former is available in feather icons, but not the latter. On Thursday I quickly "designed" the trash restore icon and sent it to Arne. Including some of Arne's feedback and my adjustments, this took 15min max. I used air quotes for "designed" as I created the SVG purely with a text editor, starting from the base trash icon :D So expect Arne to push this icon here soon.
- `<FaToggleOn />` and `<FaToggleOff />`: These are available in feather icons. I assume Arne kept the font awesome ones because of the colored background in the design template was easier to implement with that. Though I think the current version of it in this PR is not ideal anyway. I think using the feather icons is fine. Or, in order to get a nice animation, one could very easily write one's own SVG. But that's beside the point, there is not really a reason to use font awesome here.
- `<FaTools />`: this is just a placeholder for a page that, as far as I can tell, no one can easy. It's easy to replace that with anything, but very similar icons also exist in feather and hero.

So: really only one icon that's clearly missing in feather+hero (but which was easy to create). Compared to the 24 feather icons that are used in this PR, that's not too terrible of a ratio (albeit not your 1-2 from 100).
And for some Tobira stats: we use 97 feather icons, 12 hero icons and 2 self made ones, which were also super trivial to self-make.

And lets not forget that feather+hero wasn't just suggested for the fun of it: it looks better (TM). Well, at least according to Lisa; and I agree with her. The free font awesome icons are often too thick for the look we are going for. Feather+hero look a bit more modern. Font awesome also has a slimmed down version of all icons, but that's not free. And both of these icon sets look very similar; otherwise we wouldn't even have considered mixing two!

Again, I fully get what you are saying and agree with the direction: having one icon library with everything in it is super helpful and prevents us having a wild mix of icons. But I just don't think it's nearly as big of a deal as you describe it to be. I worked under these constraints for the past almost 3 years and it's fine. Yes, let's make sure that devs are not throwing other icon packs into the mix. And yes, if these projects accept contributions again, lets try to push our icons upstream. But other than that, I'd suggest not worrying about that and using the icons that our designer suggested -- just switching to completely different icons would only make things worse IMO.

2023-07-03 15:17 UTC, LukasKalbertodt commented
> Care to teaser a bit more for those who were not involved in those talks? :grin:

Sorry, didn't mean to be secretive. Need to constantly remind myself to communicate these things more openly in the community :persevere: 

In short: Tobira developed one set of grey tones organically over its development, long before Lisa suggested her final design. In that design, she defined a different set of grey tones. (We are just talking brightness.) Lisa's set of grey tones is used in the designs for Editor, Studio and Tobira. When mostly implementing Lisa's design in Tobira earlier this year, we did not adjust all the grey tones. That was mostly an oversight on my part, but also: Tobira already had grey tones, so it would have added more work. 
What we now tried to do is unify these sets of grey tones so that: we have one set for all apps, but without having to redo all of Tobira AND without changing Lisa's designs too much AND without introducing too many different tones. And I think we now succeeded in doing that. You can expect a PR soon, at least for Tobira. 

If you want more details, I've written a document about it [here](https://hackmd.io/GH97PPMkTTmDV8RJA-3I9Q?view). Note: this is German AND was intended to be just a private document to @owi92 in response to https://github.com/elan-ev/tobira/pull/895.

2023-07-04 08:14 UTC, Arnei commented
Trying to make a comprehensive list of the issues reported so far

- Vertical scrollbar appears on all pages, it should not if possible
	- Possible solution: Make page height scale better with view height
	- Appears on e.g. 3440x1440 with 100% zoom level but a UI scale factor of 1.5
- The new color scheme should have a higher contrast
	- Reasoning: Currently strenuous to use for extended periods of time
	- Reasoning: Accessibility
- The new color scheme is not neutral anymore, it should switch back to neutral (greyscale)
	- Reasoning: Neutral colors allow the editor to fit better with a variety of tools
	- Some color may be kept for highlighting certain important elements, but should be used sparingly
	- Same for dark mode
- Lots of wasted space in the Cutting view, use more page height
	- Possible solution: Don't hard limit the max height of the video area
- Videos in the Cutting view (and Subtitle View) now have a black background
	- Possible solutions: Keep, make like Thumbnail view, replace black with page bg color
	- Which solution to choose?
- Icons not all from the same set. What to do?
	- Ongoing discussion
- Enlarge on hover "feel" is not in line with Studio/Tobira
	- Possible solution: Do it like Studio/Tobira, e.g. color changes
		- Need to think about if this works for the Editor
- Metadata view, not all elements have the same border color on focus. Unify.
- Keyboard control view, box shadow too strong. Make less prominent
- ~Logo SVG issues~
	- Worked on in seperate issue #1096
- Play button icon in play button feels off-center
- Track View, shrink track containers to avoid scrolling

2023-07-04 08:14 UTC, Arnei commented
> I would shrink the track-containers, at least on narrow screens, such that this page doesn't scroll unless on a really small screen. Maybe use percentages or something comparable?

Are you referring to vertical scrolling, horizontal scrolling or both? Also keep in mind that there could be more or less than two tracks.

> but yes, I think there are only 5 font awesome icons left

Akshually, it's 6 icons. `FaPhotoVideo`, the main menu icon for the Thumbnail View, is also still there.
And the main menu icon for the subtitle view is from Material Design, so neither FontAwesome nor Feather. 

> <FaToggleOn /> and <FaToggleOff />: [...] But that's beside the point, there is not really a reason to use font awesome here.

I believe that the background color change is central to a good toggle. Feather does not seem to provide that. I'm also really not a fan of toggles where the circle is "inside" the ellipse, it does not fit my intuition on toggles.

2023-07-04 09:17 UTC, Arnei commented
> What about just FiImage?

I guess that could work? I'll go with that and see if anybody complains.

> So there was already icon mixing before switching to Feather+Hero :o

Nah, it was all FontAwesome before. I just took the opportunity to resolve #897.

> What about "message-square" from feather or "annotation" from hero? I found none that was exactly the same icon as the one you are currently using. might be worth creating a custom one here again :/

I really would like the subtitle icon to look highly similar to the material design one. I'd also argue that using the material design one here is not jarring (unlike e.g. the thicker FontAwesome icons), but I'm admittedly a poor judge of that.

2023-07-04 09:49 UTC, LukasKalbertodt commented
> Nah, it was all FontAwesome before. I just took the opportunity to resolve #897.
Ah, I see.

> I really would like the subtitle icon to look highly similar to the material design one. I'd also argue that using the material design one here is not jarring (unlike e.g. the thicker FontAwesome icons), but I'm admittedly a poor judge of that.

I would also say it's fine, but I agree with Lars here: starting to pull in even more external icons is a slippery slope and then we end up with lots of different ones. What do you (all) think of this one?

![subtitle](https://github.com/opencast/opencast-editor/assets/7419664/bcfe9b87-f1aa-49d9-9389-160f5ff95f6a)

To maybe shed a bit of light on how I create these icons: I just pick an icon from feather that has at least one similar element in it (this time I used "mail"). Then I open it in my text editor and remove the parts that I don't want. Finally, I added some `<polyline>` entries. With the attributes on the `svg` element, it immediately keeps the look of feather icon. And: feather icon designed all icons on a 24x24 grid, meaning that all coordinates are just integers below 24. So... there is not a ton to "design" anymore if you already have an idea how it should roughly look (like i had with trash restore and subtitle).

2023-07-05 15:13 UTC, LukasKalbertodt commented
I just talked to Olaf, and we briefly talked about this. He will still look at this himself (likely next Monday). But he already gave  initial thoughts on the main issues I told him:
- Accessibility wins over design: if contrast is too low, then we certainly need to increase it to be accessible.
- He is on board with making it less colorful. We think a very easy win is to remove the color (i.e. make it grey) from: the waveform and all, except for the active one, main menu entry.
- Regarding the icons he just suggested that this might be a broader discussion to be had? And he brought up discussing this at the DACH meeting in Bern. 

So I think quite a few issues listed in Arne's summary comment could already be fixed, as everyone seems to agree on those.

2023-07-10 15:12 UTC, oas777 commented
Thanks, Arne. In order not to lengthen and intensify the discussion, I'll try to keep it short, apologies for failing and possible repetitions:

**General impression**
- Colors: I agree, it was too colorful overall, the latest changes made it better.
- Enlarge on hover-over: I could argue with consistency, but I admit I also hate this.
- Font(s): I look like there a different fonts being used:
![image](https://github.com/opencast/opencast-editor/assets/1752342/73b1fadb-3863-471b-971b-3e10a5e2752e)
I'm not saying that is the case, but it looks uneasy.
- Wording: Is it OK to say "OKAY"? 
- DE/EN: Some hover-over tips are English, while there is no English version to switch to, is there?
- Logo/text: Better with the changes made, but with 2560x1440 "Editor" looks a bit rough (just like some of the other texts...) on my Windows system.
![image](https://github.com/opencast/opencast-editor/assets/1752342/95064358-6611-4c60-8a61-fc7bb497a343)
![image](https://github.com/opencast/opencast-editor/assets/1752342/8c12ec17-e52f-4198-b53a-b7ef779bd00d)
- Icons: Not going to comment here for the sake of focusing on design. And too hot a topic, it seems.

**Schneiden**
- No stripes for "deleted" areas.
- Remove black background but keep videos spaced for broader timeline
- With the new grey mode, it's hard(er) to tell whether "Vorschaumodus" is activated or not.
- Do we need the grey background for time, "Play", and "Vorschaumodus"?

**Metadaten**
- Cannot enlarge "Beschreibung" vertically while the icond
![image](https://github.com/opencast/opencast-editor/assets/1752342/fc2c8013-dbdc-4b08-b7f0-14f2d45fbffd)
- Do we need the grey background when choosing a "Lizenz"?
![image](https://github.com/opencast/opencast-editor/assets/1752342/faaee013-9788-4e74-9ce7-983d17bbf8cb)
- What's the deal with the subline of "Startdatum"? Why is it highlighted upon hover-over? Why is it different from the "Erstellt am" underline
- ![image](https://github.com/opencast/opencast-editor/assets/1752342/c182680f-096e-4eff-b4c3-04584700f268) - seriously?

**Spuren**
- If there is an overall motif of "elements" across "Untertitel" and "Fertigstellen" here in Editor and in Studio (and I am in favor of this), these elements should be coherent in resolution and design. 
![image](https://github.com/opencast/opencast-editor/assets/1752342/85af2a69-f7ea-40a5-8a56-65caaf096da5)
![image](https://github.com/opencast/opencast-editor/assets/1752342/d06a6b5b-ff23-4ec9-9c5c-81e188f8aafc)
![image](https://github.com/opencast/opencast-editor/assets/1752342/9bd40e2f-33da-4b87-a42f-cc7be88b8dd9)

**Untertitel**
- Why is there an American flag on Firefox and "US" in Chrome?

**Settings**
- I'm missing a sort of "back" option here.

2023-07-11 14:15 UTC, Arnei commented
Thanks for the extensive review. Haven't gotten around to each of your points yet, but I already wanted to reply to some of your questions:

> Wording: Is it OK to say "OKAY"?

As far as I am aware, "Okay" is acceptable in both english and german, although it's maybe a bit casual? Do you have a suggestion in mind?

> DE/EN: Some hover-over tips are English, while there is no English version to switch to, is there?

While there is indeed an English version, you are correct in that you cannot easily switch to it. The language of the editor is currently completely determined by your browser settings. If some strings are in english, that is because english is the default language and the german translators haven't gotten around to translating the strings yet (or the translations have not yet been automatically merged). In the future, adding a language selector would be great.

> +1 for removing stripes for "deleted" areas.

The stripes in the "deleted" areas are supposed to help colorblind user to more easily differentiate between "deleted" and "not-deleted" areas. So if we want to remove the stripes, I would like to have something else that can fulfill the same functionality as the stripes. So far I haven't been able to come up with anything better.

> Do we need the grey background for time information, "Play", and "Vorschaumodus"?

The grey background does help visually differentiate the video controls from the timeline actions. This could be accomplished in other ways, but I personally think the grey background is fine. Any specific gripes you have with it?

> Why is there an American flag on Firefox and "US" in Chrome?

Flags are represented through unicode characters, so their appearance will differ based on the browser and operating system.

The editor can also be configured to not show any unicode flags, since there were concerns on how country flags do not appropriately represent languages.

> Talking about messy... maybe also try to organise this with "elements"? Talking of which, can't we make the "elements" coherent across "Schneiden", "Spuren", and "Vorschaubild"? Allign them coherently vertically and horizontally?

Interesting proposition. I think it is fine to have the video elements appear differently in different views. For example, in "Tracks" the video elements are each in their own box because the user can interact with them seperately. Conversely, in "Cutting" the video elements are grouped together because the user can only interact with them as a whole (for example, the user can't only cut the presenter track, they always have to cut both presenter and presentation).

2023-07-12 18:29 UTC, lkiesow commented
> While there is indeed an English version, you are correct in that you cannot easily switch to it. The language of the editor is currently completely determined by your browser settings. 

You can force a language by appending something like `?lng=en` in the URL

2023-07-12 18:57 UTC, lkiesow commented
>>   +1 for removing stripes for "deleted" areas.
>
> The stripes in the "deleted" areas are supposed to help colorblind user to more easily differentiate between "deleted" and "not-deleted" areas. So if we want to remove the stripes, I would like to have something else that can fulfill the same functionality as the stripes. So far I haven't been able to come up with anything better.

Experimenting a bit, I think that just having less stripes already makes the UI look cleaner. So maybe this is a compromise? Plus that I would still be a huge fan of removing the blue background from the waveform. Something like:

![Screenshot from 2023-07-12 20-48-14](https://github.com/opencast/opencast-editor/assets/1008395/98a7d0a9-7190-49d5-9664-f1e7ac4217e2)

I still think this can be improved more by experimenting a bit more with the borders of the waveform. I would probably go with a bit less contrast there. And I suggest reducing the height of the waveform. It's too large for it just being a single stream. Looking at other editors, you get a mililar ratio, but there you will usually have several audio streams.

2023-07-12 19:05 UTC, lkiesow commented
> * Time picker:
>    ![image](https://user-images.githubusercontent.com/1752342/252377740-c182680f-096e-4eff-b4c3-04584700f268.png)
>    Seriously?

:rofl: 
And I agree that I dislike it.
My strong personal preference is still to use an [`<input type="datetime-local">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) which is widely supported by now and gives you a native date and time picker experience both on desktop and on mobile.

2023-07-12 19:08 UTC, lkiesow commented
![Screenshot from 2023-07-12 21-06-48](https://github.com/opencast/opencast-editor/assets/1008395/3b861c68-3330-48b0-8025-97ba112962cf)


That button + icon doesn't look right.

2023-07-12 19:26 UTC, lkiesow commented
![Untitled](https://github.com/opencast/opencast-editor/assets/1008395/ed8c3fb1-cfde-47b0-bdf8-6ee8b3b43fac)

- Spacing looks weird.
  - Lots of unused free space in random spots
  - UI elements form a big cross on the screen
- Used area in top and bottom are not aligned
- You don't really need the waveform on this screen, but it's the centerpiece of the whole user interface
  - Maybe reduce the height and put it at the bottom? (Maybe along with the player?)
  - Or remove it?
- Padding on the button is missing

2023-07-12 19:38 UTC, lkiesow commented
![Screenshot from 2023-07-12 21-29-55](https://github.com/opencast/opencast-editor/assets/1008395/76218c3b-cc0b-4546-a851-5361d36a0759)

No! :D

Not only does this not fit the style, but the contrast is bad and why has this become the only modal dialog in the editor. The confirmation for discarding changes or starting processing are no modal dialogs. Can we get what we had before? It actually fit way better into the overall look and feel.

2023-07-12 19:41 UTC, lkiesow commented
![Screenshot from 2023-07-12 21-33-16](https://github.com/opencast/opencast-editor/assets/1008395/44067760-a1be-45b4-80ba-5d694846f9d0)

- Title and description of workflows are not aligned
- Why is the left button larger?
- Why is there so much space between text and icon on the left button?
- Why is the icon for start processing a database symbol?

2023-07-12 19:42 UTC, lkiesow commented
![Screenshot from 2023-07-12 21-35-13](https://github.com/opencast/opencast-editor/assets/1008395/e012c07e-cae9-4bee-8c2a-d01e536ff4c4)

Clicking on settings doesn't do anything in this view.

2023-07-13 17:53 UTC, oas777 commented
> > While there is indeed an English version, you are correct in that you cannot easily switch to it. The language of the editor is currently completely determined by your browser settings.
> 
> You can force a language by appending something like `?lng=en` in the URL

The reason I mentioned this was not so much functional, but because of coherence as part of the design update: Tobira provides the option to actively switch languages, whereas Editor (and Studio?) do not. Is this something we can/should address?

2023-07-13 17:55 UTC, oas777 commented
> > * Time picker:
> >   ![image](https://user-images.githubusercontent.com/1752342/252377740-c182680f-096e-4eff-b4c3-04584700f268.png)
> >   Seriously?
> 
> 🤣 And I agree that I dislike it. My strong personal preference is still to use an [`<input type="datetime-local">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) which is widely supported by now and gives you a native date and time picker experience both on desktop and on mobile.

+1 for the one Lars suggests.

2023-07-13 18:05 UTC, oas777 commented
> ![Screenshot from 2023-07-12 21-06-48](https://user-images.githubusercontent.com/1008395/253075598-3b861c68-3330-48b0-8025-97ba112962cf.png)
> 
> That button + icon doesn't look right.

While it's hard to see anything in this screenshot, I think the navigation to the left also fails to highlight the functionality/step you're currently in (here: "Tracks"). Which it should, shouldn't it?

2023-07-13 18:12 UTC, oas777 commented
> ![Untitled](https://user-images.githubusercontent.com/1008395/253078518-ed8c3fb1-cfde-47b0-bdf8-6ee8b3b43fac.jpg)
> 
>     * Spacing looks weird.
>       
>       * Lots of unused free space in random spots
>       * UI elements form a big cross on the screen
> 
>     * Used area in top and bottom are not aligned
> 
>     * You don't really need the waveform on this screen, but it's the centerpiece of the whole user interface
>       
>       * Maybe reduce the height and put it at the bottom? (Maybe along with the player?)
>       * Or remove it?
> 
>     * Padding on the button is missing

I called this one "messy" as part of https://github.com/opencast/opencast-editor/pull/1079#issuecomment-1629168742 where I suggested to handle video and other "elements" consistently. Which I think would remedy some of Lars' concerns.

2023-07-14 08:25 UTC, Arnei commented
> The reason I mentioned this was not so much functional, but because of coherence as part of the design update: Tobira provides the option to actively switch languages, whereas Editor (and Studio?) do not. Is this something we can/should address?

Studio also provides the option to actively switch languages.

I am also in favor of addressing this, but maybe not as part of this PR. In my mind it is a functional feature, and in my initial comment in this PR I claimed that this PR would focus on the visual changes.  So I'd suggest working on adding the option after this PR is in a good state.

2023-07-18 10:40 UTC, Arnei commented
As information for people who are only subscribed to this PR: There is additional discussion going on in #1106 and #1107.

2023-07-18 21:24 UTC, oas777 commented
> 

Took "language switching" to https://github.com/opencast/opencast-editor/issues/1108.

2023-07-19 15:37 UTC, LukasKalbertodt commented
Just noticed: the header of the current deployment of this PR has neutral80 as background, but the Lisa's design uses neutral60 for Studio and Editor. Studio & Editor already use a very similar logo. If we also use the same color and potentially language+colorscheme buttons (see #1108) then the header would look extremely similar, which would be great for coherence I suppose.

2023-07-25 11:23 UTC, Arnei commented
Time for a short status overview. I think I either responded or implemented most of the feedback you have given. Below is a short list of the remaining issues. If I missed any of your issues, please shortly reiterate them.

- The video designs discussed in #1106 and #1107.  I did add a white canvas around all videos in [56fd3c6](https://github.com/opencast/opencast-editor/pull/1079/commits/56fd3c6d39d62562699458456a75aa21fcd2d87f), waiting for feedback on that, if it's too much or not enough.
- Do want to do #1108 in this PR or leave it for a follow-up PR? I'm asking because it would technically be a feature, but I highly doubt anyone would be against a language picker. So I'm probably just going to go ahead with it.
- The Thumbnail View layout still isn't great, especially not for single video events. Getting input from a pro designer (Lisa) might help us tremendously here.

2023-08-10 10:44 UTC, lkiesow commented
To not dig into this too deep again, let me just ask here:
Are we now using the larger icon library Lukas suggested on Matrix?
That sounded like a very good compromise.

2023-08-10 11:08 UTC, lkiesow commented
On the metadata view, having no border for the non-editable fields looks a bit odd. In particular, if the field is also empty (like the publisher in the following example):

![Screenshot from 2023-08-10 12-58-08](https://github.com/opencast/opencast-editor/assets/1008395/b52fd182-7a11-4c3d-a6b9-1706ee14378e)

- Maybe keep the border and just gray-out the field? Or at least add a gray border?
- And maybe hide non-editable, empty fields?

2023-08-10 11:12 UTC, lkiesow commented
The size of the button in the track selection changes when you click on them. That's probably not intentional. 

![Screenshot from 2023-08-10 13-02-16](https://github.com/opencast/opencast-editor/assets/1008395/693c52e5-a155-4d1a-a509-7a7c551ada6d)

2023-08-18 14:06 UTC, oas777 commented
> On the metadata view, having no border for the non-editable fields looks a bit odd. In particular, if the field is also empty (like the publisher in the following example):
> 
> ![Screenshot from 2023-08-10 12-58-08](https://user-images.githubusercontent.com/1008395/259720497-b52fd182-7a11-4c3d-a6b9-1706ee14378e.png)
> 
>     * Maybe keep the border and just gray-out the field? Or at least add a gray border?
> 
>     * And maybe hide non-editable, empty fields?

This has been solved, right? For the empty "non-editable" metadata field cf. https://github.com/opencast/opencast-editor/issues/1080.

2023-08-18 14:50 UTC, oas777 commented
Arne, thanks for wrapping this up. In addition to your [summary above](https://github.com/opencast/opencast-editor/pull/1079#issuecomment-1649645381) I have some final remarks:

- I'm not so happy we seem to have given up on the "blue" completely. While the argument for "grey" (use in other systems) is valid, the argument for coherence with Studio and (in) Tobira is valid as well, isn't it? Any chance of some light "blue accents" Lars and Lukas mentioned?
- Subtitles: Language abbreviations are not centered in the respective circle: 
![grafik](https://github.com/opencast/opencast-editor/assets/1752342/0cb0afa4-fd3e-425a-9978-50270461b1cb)
- Metadata: Any thoughts on searching the correct "Series" once we have thousands of videos and >100 series called "Analysis..."?
- Metadata: Pity the date picker doesn't have an "OK" button to the actual metadata field.
- Talking about "OK": Where was the "OKAY" I thought was inappropriate wording in https://github.com/opencast/opencast-editor/pull/1079#issuecomment-1629168742?
- Tracks: "Inactive" should be "inactive".
- Settings: Still would like to see an "OK" or "Back" option instead of clicking back to the left navigation.

2023-08-18 17:49 UTC, lkiesow commented
> > To not dig into this too deep again, let me just ask here:
> > Are we now using the larger icon library Lukas suggested on Matrix?
> > That sounded like a very good compromise.
> 
> As of now, no we do not. Talked with Lukas about this and he had some quality concerns he wanted to alleviate first.

For everyone else: We are talking about the Lucide icon set which is a fork of Feather icons
- https://lucide.dev/
- https://github.com/lucide-icons/lucide

I still have concerns about using Feather if we have problems getting things into that library and think Lucide is a good compromise if we don't want to stick to FontAwesome. Lucide is much more active compared to Feather. It also seems well maintained.

2023-08-21 12:22 UTC, Arnei commented
> I'm not so happy we seem to have given up on the "blue" completely. While the argument for "grey" (use in other systems) is valid, the argument for coherence with Studio and (in) Tobira is valid as well, isn't it? Any chance of some light "blue accents" Lars and Lukas mentioned?

Experimented a bit, but couldn't find anything I really liked. Below are some tests. Maybe it'll be best to ask Lisa for her opinion on this.

_|_
-|-
![Bildschirmfoto vom 2023-08-21 13-31-20](https://github.com/opencast/opencast-editor/assets/14070005/a6caf871-8915-4fe1-a60a-b02a5e42d067) | ![Bildschirmfoto vom 2023-08-21 13-30-34](https://github.com/opencast/opencast-editor/assets/14070005/aca3facb-5285-4111-808f-292cb3af7e09)

2023-08-21 12:38 UTC, Arnei commented
> Metadata: Any thoughts on searching the correct "Series" once we have thousands of videos and >100 series called "Analysis..."?

So the series names are all so similar that it is impossible to keep them apart by name alone? Then we're probably not getting around fetching and displaying additional metadata about the series to help differentiate them, but which metadata would be relevant?  
I'd say this question is beyond this PR and worth it's own github issue.

2023-08-21 12:55 UTC, Arnei commented
> Talking about "OK": Where was the "OKAY" I thought was inappropriate wording in https://github.com/opencast/opencast-editor/pull/1079#issuecomment-1629168742?

Iirc in one of the "Finish" modals that got retconned because the look and feel just wasn't great.

> Settings: Still would like to see an "OK" or "Back" option instead of clicking back to the left navigation.

Since we ultimately want to get rid of the settings page and split it into header options like in studio, putting work into a "Back" option does not seem worth it.

2023-08-22 13:13 UTC, LukasKalbertodt commented
Sorry for the late reply, but now finally, regarding the icons: 

Last time I commented I hadn't had time to look properly into Lucide icons and just knew basic, promising facts. I had two worries: (a) that Lucide is not a strict superset of Feather, but modified icons, and (b) that Lucide contains low quality icons and just "merges anything". I now took some time to take a closer look and both of these worries have been resolved.

<details>

<summary>How I resolved both of my worries</summary>

It really seems like the icons the pack inherited from Feather were not changed. It's hard to verify as the files are sometimes different, but just in insignificant ways that don't affect how the icon looks. Also they write [here](https://lucide.dev/guide/comparison):

> When we forked, we didn't remove any icons, but some icons have been renamed.

Again, it's not explicitly stated what I'm looking for, but it sure just sounds like they were not meaningfully changed. All specific icons I compared were exactly the same. One thing I found that seems to suggest that icons WERE modified is [this](https://github.com/lucide-icons/lucide/issues/169). Tho it's also never explicitly said.

In the end, maybe this question of whether it is an exact super set is probably irrelevant. There don't seem to be big differences and the general design language is clearly the same and thus these icons fit into the designs by Lisa.

Regarding the second worry of Lucide just accepting any random icon PR: that's not the case. I have read through some of their PRs and it seems very professional. They do discuss new icons, sometimes extensively, request changes and have lots of cool automation in place to help with icon reviews. They also have a good design guideline that all icons must follow. Finally, skimming over all icons, no icon stood out as bad to me.

</details>

So with this I would suggest we can ignore Feather and just use Lucide. In the coming weeks, I will go through all icons in Studio and Tobira and for those that are custom or from Heroicons, I will check whether a suitable icon already exists in Lucide. If that's not the case and it is a custom icon, I will contribute it upstream unless it's a super application-specific icon. If I succeed in removing all Heroicons, then that's even better! In that case, we only have exactly one icon library to take icons from! 
Once I'm done, I will write down the Icon library in the readme of appkit; I will tag Lars and other interested people in that PR. I hope this is satisfactory for everyone!

But I guess this editor PR can already switch to Lucide.

2023-08-25 09:12 UTC, lkiesow commented
https://github.com/opencast/opencast-editor/assets/1008395/7b142e64-10ca-4021-a20e-33129a4bdf07

It seems like the theme selection is now broken when you first go to the editor.

2023-08-25 09:18 UTC, lkiesow commented
![Screenshot from 2023-08-25 11-16-01](https://github.com/opencast/opencast-editor/assets/1008395/35f5da58-9f35-4f9c-8b41-0ef35ff6bbc6)

The language is initially selected automatically. Similar to the auto mode for appearance, the language should have an auto option as well which automatically follows the system/browser language.

2023-08-25 09:20 UTC, lkiesow commented
![Screenshot from 2023-08-25 11-14-33](https://github.com/opencast/opencast-editor/assets/1008395/c7efde9d-bbfd-4654-a67c-d63f59eb18f6)

Studio and editor should kind of look alike, but they are using different colors, different icons, different padding and different texts in the header where it is very noticeable.

This is less of a problem for the body which is very much different anyway.

2023-08-25 09:37 UTC, oas777 commented
> Studio and editor should kind of look alike, but they are using different colors, different icons, different padding and different texts in the header where it is very noticeable.
> 
> This is less of a problem for the body which is very much different anyway.

Not sure I understand this comment - to what issue/comment does it refer? And what does it say? Is the alignment good? Bad? Unfinished?

2023-08-25 11:32 UTC, lkiesow commented
Part of the goal of redesigning editor and studio was to make them look similar and to use the same style, wasn't it? If you just look at the headers of both you see in the picture I posted along with my comment you see some stark differences in the new designs though. With the new designs:

- Studio and editor use different icons for the menu appearance
- Studio and editor use different names for the same functionality e.g “Shortcuts” vs “Keyboard Controls”
- Studio and editor use different colors/gray tones for the texts
- Studio and editor use have different paddings around the logo

The header is probably the most noticeable part of both tools and if the goal was to make the tools look alike and the most noticeable part doesn't I think that's an issue.

I hope that clarifies the issue to you, @oas777? Because to be honest, I don't quite understand your questions about my issue report :see_no_evil:

2023-08-25 14:03 UTC, oas777 commented
The "misunderstanding" stems from you mentioning both the header and the body (as contrast, I admit) in your comment. And from the fact that I considered the header alignment solved because Lukas told me it would be. Over and out.

2023-08-25 19:40 UTC, lkiesow commented
Ah, okay. The screenshot is from the Studio redesign merged yesterday and the latest state of this pull request:

- https://studio.opencast.org/
- https://test.editor.opencast.org/1079/2023-08-24_15-23-41/

2023-08-28 14:02 UTC, lkiesow commented
> Thinking about an auto option for languages, I don't recall seeing that on other websites where you can select your preferred language.

Just to give you an example, here is my language selector from Firefox:

![Screenshot from 2023-08-28 15-44-40](https://github.com/opencast/opencast-editor/assets/1008395/384903ae-beea-4c37-955e-adbfa3575f91)


> So I'm wondering why we would want that. Besides it being an option in the theme dropdown.

But to give you a better reasoning: Imagine you would have to select the language you want on every single tool you are using. That would drive you insane ;-) Selecting the system language once is certainly catching most of the cases, but sometimes even I switch languages and not having to do that in several tools would be great.

But more than that, I would also argue about consistency. The theme selector already has an auto mode, making the settings dependent on the system settings. Why would you want to have an auto mode for one and not the other setting which is dependent on system settings?

![Screenshot from 2023-08-28 15-45-43](https://github.com/opencast/opencast-editor/assets/1008395/5c08766c-b9c4-4b48-9dca-21bb5bb520ce)

2023-08-29 08:00 UTC, Arnei commented
I understand, thanks for the detailed explanation.

Unfortunately, it seems the translation library we use (react-18next) does not support an auto option out of the box. We certainly could work around that and make our own auto mode somehow, but it seems to me like that would take more time than I am willing to spent on it in this PR. Best left for another time.

2023-08-31 08:25 UTC, Arnei commented
If people are happy with this PR in general and there are no more requests for large scale changes, it would be great if we could get it approved and merged. Since this PR touches most parts of the editor, it also blocks a lot of other PRs. Getting this PR merged would free those up. And getting this PR merged does not mean the redesign has to be done and over with, we can still make follow-up PRs for smaller scale changes.

2023-08-31 21:05 UTC, lkiesow commented
> Unfortunately, it seems the translation library we use (react-18next) does not support an auto option out of the box. We certainly could work around that and make our own auto mode somehow, but it seems to me like that would take more time than I am willing to spent on it in this PR. Best left for another time.

If I remember correctly, it does support that to some extent: It already selects the language automatically, if none is stored in the local storage. So maybe just store to auto-mode separately and make sure to remove the stored i18m language before loading i18m.

But I'm absolutely fine with moving that to a separate patch.

2023-09-12 13:45 UTC, owi92 requested changes
Ok so I've looked over the code changes and left some comments, but tbh these are just personal preferences and I wouldn't say that you actually need to address any of these.

I also took another look at the deployment and noticed a few small things that should probably get fixed:
- High contrast mode:
  - (dark only) The menus for language and appearance should have a visible border. Since they have the same background color as the general background, they look a little weird without that: <img width="517" alt="Bildschirmfoto 2023-09-12 um 15 33 59" src="https://github.com/opencast/opencast-editor/assets/94838646/27bc3281-6fff-417b-ad52-e650332e8803">
  - (dark and light) The subtitle picker barely has any contrast on hover: <img width="333" alt="Bildschirmfoto 2023-09-12 um 12 09 21" src="https://github.com/opencast/opencast-editor/assets/94838646/57c62a85-3ed0-4d9b-9132-eb6b4204684c"> <img width="333" alt="Bildschirmfoto 2023-09-12 um 12 10 13" src="https://github.com/opencast/opencast-editor/assets/94838646/573ce30d-ac47-4266-bbd3-ba9159d31752">
- Metadata:
  - the translation for `portugese` is missing: <img width="731" alt="Bildschirmfoto 2023-09-12 um 15 38 51" src="https://github.com/opencast/opencast-editor/assets/94838646/dc1760bd-7eaa-48c2-98d6-ec9ceaffb3bf">
- Subtitle editor:
  - there's a cut-off button: <img width="782" alt="Bildschirmfoto 2023-09-12 um 15 40 38" src="https://github.com/opencast/opencast-editor/assets/94838646/cecedef8-a83e-4c42-8b40-e1dde9f48961">
  - I think the timeline overview could use some margin on the bottom. Without, it's kind of hard to notice: <img width="1326" alt="Bildschirmfoto 2023-09-12 um 15 44 06" src="https://github.com/opencast/opencast-editor/assets/94838646/5b9b2009-aae6-4e9f-9eaa-5e4ae55dc65a">

2023-09-12 13:45 UTC, owi92 commented on src/main/VideoPlayers.tsx
> +  // );
Another one, though as with the others, maybe you have a reason for keeping this around.

2023-09-12 13:45 UTC, owi92 commented on src/main/VideoPlayers.tsx
> +    );
Nothing wrong with this, but you could do sth like
```
return errorState
  ? <div css={errorBoxStyle} role="alert">
            <span>{t("video.loadError-text")} </span>
   </div>
  : <ReactPlayer (...) />
```

2023-09-12 15:48 UTC, Arnei commented
Thanks for the review Ole

> (dark only) The menus for language and appearance should have a visible border. Since they have the same background color as the general background, they look a little weird without that: 

Agreed, will look into that. Will likely have to fix it in appkit though. Could this also be done in a follow-up PR or would you consider this a blocker? 

> (dark and light) The subtitle picker barely has any contrast on hover: 

Should be better now.

> the translation for portugese is missing: 

Should be fixed now (for english)

> Subtitle Editor and Code style

While these are valid concerns, most of these already exists prior to this PR. Thus, it should not be the responsibility of this PR to fix them, let alone discuss which code styles we want to pursue. We can address these topics in separate issues.

2023-09-12 16:52 UTC, gregorydlogan commented
While I haven't looked at the code, the UI itself looks good to me.

2023-09-12 21:03 UTC, owi92 commented
> Agreed, will look into that. Will likely have to fix it in appkit though. Could this also be done in a follow-up PR or would you consider this a blocker?

Fair point, and I don't consider this a blocker.

> 

    (dark and light) The subtitle picker barely has any contrast on hover:

> Should be better now.

The contrast is better, though I'd probably prefer sth like this on hover: 
(But I would also say this can be moved to another issue and doesn't need to be done in this PR, if at all)
<img width="403" alt="Bildschirmfoto 2023-09-12 um 22 57 11" src="https://github.com/opencast/opencast-editor/assets/94838646/a5f7bd46-a338-4e29-8787-ca15a9c8109d">


> While these are valid concerns, most of these already exists prior to this PR. Thus, it should not be the responsibility of this PR to fix them, let alone discuss which code styles we want to pursue. We can address these topics in separate issues.

Yeah I figured as much, especially regarding the code styles.
So I'd say this can be merged.

2023-09-12 21:03 UTC, owi92 approved these changes

2023-09-13 10:52 UTC, merged

2023-09-13 12:56 UTC, oas777 commented
I know I'm late to the game, but I'm still struggeling with the diversity of canvasses, cf. https://github.com/opencast/opencast-editor/issues/1106.

Title ("Presenter" or "Presentation) or not?
![grafik](https://github.com/opencast/opencast-editor/assets/1752342/79d2c508-8a01-484a-a592-11d5f14ff67a)
vs.
![grafik](https://github.com/opencast/opencast-editor/assets/1752342/6804f5d6-09c2-46de-9527-f525b98cb9b9)
vs.
![grafik](https://github.com/opencast/opencast-editor/assets/1752342/1fc21bc0-8a78-40c9-ac5b-d5803cc9652e)

Functions/symbols below or to the right?
![grafik](https://github.com/opencast/opencast-editor/assets/1752342/a361d04e-e9e5-4a53-8b32-84d6985c9ac4)
vs.
![grafik](https://github.com/opencast/opencast-editor/assets/1752342/876ccdc9-042b-4818-a72e-8ad45230b040)

And, as a consequence, size, resolution, and appearance are very diverse over only three "elements" ("Cutting", "Tracks", "Thumbnail")

2023-09-13 12:57 UTC, oas777 commented
PS: I'm in favor of titles in every canvas and symbols to the right, a vertical alignment as a consequence.

2023-09-13 13:35 UTC, Arnei commented
Created a new issue for the symbols below/to the right in #1157 (trying to move discussions out of this really long thread).