Don't show track view if there is only one track
opencast/opencast-editor pull request #1209
Opened 2023-11-07 09:23 UTC by Arnei

If an event has only a single track, you cannot deselect that track, so the track view is rather pointless in that case. Therefore, we might as well not show it.

Fixes #1205.

2023-11-07 11:18 UTC, LukasKalbertodt approved these changes
Code looks good and seems to work (see https://test.editor.opencast.org/1209/2023-11-07_09-24-17/?mediaPackageId=ID-nasa-earth-4k)

2023-11-14 14:15 UTC, lkiesow commented
It might still be confusing to users when part of the tooling just silently disappears.
Maybe just adding an info box to the track selection would actually be better?
There you could put that this tool is disabled and why.

2024-04-26 11:38 UTC, KatrinIhler requested changes
Here only the info box thingy is still outstanding. Requesting changes to accurately represent the state.

2024-05-13 13:46 UTC, Arnei commented
Basic info box. Suggestions for phrasing are welcome :)

![Bildschirmfoto vom 2024-05-13 15-45-26](https://github.com/opencast/opencast-editor/assets/14070005/b560e4c7-addd-43c6-b67d-876e8f418ca7)

2025-05-20 09:56 UTC, dennis531 commented on src/i18n/locales/en-US.json
> +      "noSelectionPossible": "Track selection is disabled for this video, because there are not enough tracks to deselect any.",
I would suggest providing a more precise description about the number of tracks required:

```suggestion
      "noSelectionPossible": "Track selection is disabled for this video, because at least two tracks are required to deselect any.",
```

2025-05-23 14:35 UTC, KatrinIhler commented
Repointed to develop because the new track selection was removed from 17 by #1589.

2025-05-23 14:37 UTC, KatrinIhler approved these changes

2025-05-23 14:38 UTC, merged