Subtitle editor: Allow to change end time of segment in timeline by drag and drop
opencast/opencast-editor pull request #1316
Opened 2024-04-19 13:58 UTC by snoesberger

In the subtitle editor timeline, it was only possible to change the start time of a segment by drag and drop. This change makes it possible to change the end time in the same way.

Resolves #1314

2024-04-26 12:04 UTC, KatrinIhler commented
It's a bit unfortunate that I can't test this just because the ICLA hasn't been processed yet. :sweat_smile:

2024-04-30 08:52 UTC, snoesberger commented
I filled in the ICLA a week ago, but haven't received a confirmation yet.

2024-05-06 18:21 UTC, lkiesow commented
> It's a bit unfortunate that I can't test this just because the ICLA hasn't been processed yet. 😅

Maybe to avoid future confusion about this, a few words about the test deployment, which absence I think you are complaining about. First, you can always just clone this and run `npm start` locally.

Second, I think here is a misconception that the failing ICLA test has something to do with the missing test deployment. Since that is deploying code, for security reasons, it's only doing that for known developers. To be more precise, it's limited to people in the team `Developers` of the Opencast organization here on GitHub:

https://github.com/opencast/opencast-editor/blob/fbae57c560a48ba997aa9cf10de3540e3f1d9973/.github/workflows/update-test.yml#L11-L12

@gregorydlogan or I can easily add more people to that group. If you want access or want someone else to have access, just let us know. @snoesberger, I've invited you to that team.

2024-05-06 18:33 UTC, lkiesow requested changes
Tried this and found a bug. It seems like you get two input fields for subtitles whenever you start a new subtitle:


https://github.com/opencast/opencast-editor/assets/1008395/85e01d0c-a1a7-4ef7-b95a-1b4cbf81afb3

2024-05-07 08:25 UTC, KatrinIhler commented
> Second, I think here is a misconception that the failing ICLA test has something to do with the missing test deployment. Since that is deploying code, for security reasons, it's only doing that for known developers. To be more precise, it's limited to people in the team `Developers` of the Opencast organization here on GitHub:

Ah, thx, I did not know this! Makes sense.

2024-05-07 09:07 UTC, snoesberger commented
> Tried this and found a bug. It seems like you get two input fields for subtitles whenever you start a new subtitle:
> opencast-editor-subtitle-two-input-fields.mp4

Thanks for testing, Lars. This is strange, I can reproduce the behaviour but only when I start the editor in development mode. If I build the editor and start the new build, only one input field is added. And I have the same behaviour when I do the same for the main branch, so it looks like this problem hasn't been added by the changes in this PR.

2024-05-30 08:52 UTC, Arnei approved these changes
Works and simplifies the code to boot, nice.

Can confirm that the concern Lars brought up is unrelated to this pull request, as it is already happening on main.

2024-08-09 08:31 UTC, snoesberger commented
I'd love to see this PR merged. Or is there still something preventing it from being merged?

2024-08-09 08:35 UTC, Arnei commented
I don't see any blockers anymore, thanks for the reminder.

2024-08-09 08:35 UTC, merged