Add cue at current time for subtitles
opencast/opencast-editor pull request #1367
Opened 2024-05-30 14:08 UTC by Arnei

Adds a hotkey (Shift+Alt+e) to the subtitle editor. It allows the user to add a new subtitle segment, based on the current time of the video.

Resolves #1313.

2024-06-14 06:56 UTC, snoesberger commented
Thanks for that. There is one small issue, every time I use a keyboard shortcut to add a subtitle segment, the special character corresponding to the shortcut is added to the new segment. I would expect it to just add a new empty segment.

This is not only true for Shift+Alt+e but also for Shift+Alt+q and Shift+Alt+a.

2024-12-19 09:43 UTC, geichelberger commented
@snoesberger I could not reproduce it. Is it still an issue for you?

2024-12-19 12:32 UTC, snoesberger commented
> @snoesberger I could not reproduce it. Is it still an issue for you?

Yes, it is still a problem, I just tried again. It depends on the keyboard language you are using. If you're using a standard German keyboard layout (de), you won't see the problem. With a Swiss-German (de-ch) or US layout I'm able to reproduce the problem in different browsers.

2025-06-17 21:09 UTC, gregorydlogan requested changes

2025-06-17 21:09 UTC, gregorydlogan commented on src/main/SubtitleTimeline.tsx
> +    {}, [currentlyAt]
This line throws an error at build time:
```
/home/greg/opencast/opencast-editor/src/main/SubtitleTimeline.tsx                                                                             
  114:22  warning  Missing trailing comma  comma-dangle                                                                                       
                                                                                                                                              
✖ 1 problem (0 errors, 1 warning)                                                                                                             
  0 errors and 1 warning potentially fixable with the `--fix` option.                                                                         
                                                                                                                                              
ESLint found too many warnings (maximum: 0).  
```

2025-06-18 07:51 UTC, Arnei commented on src/main/SubtitleTimeline.tsx
> +    {}, [currentlyAt]
Thanks, should be fixed now.

2025-08-07 16:49 UTC, merged