Fixes #1512, don't save edits with no clips
opencast/opencast-editor pull request #1517
Opened 2024-12-11 11:35 UTC by JamesUoM

Before allowing the edits to be saved/processed, check that there isn't a single segment that deletes the whole video. Otherwise Opencast will create a SMIL file with not clips and the editor WOH will fail.

2024-12-12 16:10 UTC, Arnei requested changes
I've found some things that I believe should be addressed before merging.

I'm not happy with how we present the user with the problem. Simply replacing the usual save text with a warning is not obvious at first glance and does not really make clear that it is supposed to be warning. Maybe keeping the usual text and instead adding a warning box would be better? (Could use the error boxes from appkit for that *hint hint* https://github.com/opencast/opencast-editor/pull/1392). I would also prefer to keep rendering the save button, but disable it.

2024-12-12 16:10 UTC, Arnei commented on src/i18n/locales/en-US.json
> +      "invalid-text": "The segments do not create a valid video. Either change or discard your edits if you wish to proceed. If you wanted to delete this video use the Opencast Admin UI. Contact an a
We should avoid mentioning the Admin UI. The editor can be accessed from other frontends as well, like Tobira or LMS plugins. User may not know what the "Opencast Admin UI" is, nor should they need to.

2024-12-17 15:46 UTC, JamesUoM commented
> Maybe keeping the usual text and instead adding a warning box would be better? (Could use the error boxes from appkit for that _hint hint_ #1392). I would also prefer to keep rendering the save button, but disable it.

Agree with using the error boxes. But disabling buttons is not meant to be good accessible UX design - also I did try but as they are not form elements, disabling doesn't work. The `aria-disabled` will tell screen readers that it's disabled but doesn't stop it functioning.

2024-12-17 15:50 UTC, JamesUoM commented on src/redux/videoSlice.ts
> +      if (state.segments.length === 1 && state.segments[0].deleted && state.segments[0].start === 0 &&
yes, I considered that but thought it a bit of an edge case. I will add some additional tests though.

2025-01-06 10:55 UTC, Arnei commented
My concerns have been addressed, thanks! 

> But disabling buttons is not meant to be good accessible UX design

I disagree with this as a general statement. While disabling a button *alone* is indeed not good UX, I do believe it can be valuable if there are additional measures taken that make it clear to the user why it is disabled. It then helps making clear that there indeed would be a button here that they could click, instead of having the button suddenly appear.

But apparently whether disabling buttons is a good or bad thing is a whole big discussion that I do not find worth getting into since the PR looks fine to me.

> also I did try but as they are not form elements, disabling doesn't work. The aria-disabled will tell screen readers that it's disabled but doesn't stop it functioning.

Oh good to know. That's an issue with ProtoButton from appkit, right? I'll open an issue over there.

2025-01-06 10:55 UTC, Arnei approved these changes

2025-05-21 20:52 UTC, gregorydlogan commented
If/when you fix this @JamesUoM, remember to change the branch target to `r/17.x` if you want this in a 17.x release!

2025-12-09 17:44 UTC, gregorydlogan commented
@JamesUoM this, IMO, should still be fixed.  But maybe in 18/19 since we probably don't want to change this in legacy at this point.

2026-01-06 16:14 UTC, KatrinIhler commented
@gregorydlogan Is this important enough that we should fix the conflicts and merge to 18? Otherwise I'm gonna close this.

2026-01-06 18:38 UTC, gregorydlogan commented
I mean, this kinda feels like something that should be allowed to happen, but it's also something that you're really only going to see in users who are trying to be difficult.

Can close, can refile if/when someone wants to get this in.

2026-01-07 12:58 UTC, closed without merging