Display error if a workflow is running on the event
opencast/opencast-editor pull request #348
Opened 2021-06-03 11:52 UTC by Arnei

Uses new information from the `edit.json` endpoint to stop users from making changes that could not currently be saved or processed.

Related to #171.

2021-06-07 12:48 UTC, lkiesow commented
Let's wait for https://github.com/opencast/opencast/pull/2675 to be merged

2021-08-17 11:06 UTC, lkiesow requested changes
This looks like the tool or Opencast broke (we don't want to give users that impression) while it should notify the user that things are being processed and he just has to wait:

![Screenshot from 2021-08-17 12-56-26](https://user-images.githubusercontent.com/1008395/129715364-3f2ee5b3-3d80-4fde-86fd-86df335ac23c.png)

What about [using a gears icon instead](https://fontawesome.com/v5.15/icons/cogs?style=solid) to indicate that work is in progress, and then just display the newly added (and then properly internationalized) error message?

2021-08-17 11:06 UTC, lkiesow commented on src/redux/videoSlice.ts
> +          state.error = "An Opencast workflow is currently running, please wait until it is finished."
Internationalization is missing for this.

2022-04-21 07:27 UTC, Arnei commented
The page now looks like this:
![Bildschirmfoto vom 2022-04-21 09-26-25](https://user-images.githubusercontent.com/14070005/164400119-fc744fef-a419-41df-b11d-a96dafec353e.png)

2022-06-17 19:40 UTC, merged