Added Darkmode
opencast/opencast-editor pull request #720
Opened 2022-06-21 13:36 UTC by naweidner

2022-06-21 16:08 UTC, ziegenberg commented
In my opinion, there are two issues with accessibility on the metadata tab. It's the "Contributor(s)" and the "Created" Fields. See attached screenshots for details.

_It does not meet WCAG standards for accessible text, regarding colour and contrast. The current values are 3.59 and 3.79. For an AA rating, it needs to be at least 4.5 and for an AAA rating, it needs to be 7 or higher._

![Screenshot from 2022-06-21 18-00-51](https://user-images.githubusercontent.com/856916/174846273-9bf14d1c-5fd8-45ae-bb2c-7c2a55a6da14.png)
![Screenshot from 2022-06-21 18-01-00](https://user-images.githubusercontent.com/856916/174846293-2887ff53-b6cf-437d-aa26-e0cba763eee7.png)

2022-06-22 10:05 UTC, ziegenberg commented
Thanks for the changed contrast values! This looks good now.

I only looked at the visual representation, not at the code.

2022-06-22 10:18 UTC, Arnei requested changes
* Buttons seem to generally have become bigger. I recall that when first designing the editor, many were complaining that I was always making the buttons too big, so we probably want to avoid making them bigger again :D
* The DateTimePicker modals (for e.g. "Start Date") have no dark mode.
* There is an error in the console that looks new to me: `Using kebab-case for css properties in objects is not supported. Did you mean WebkitTextFillColor?`

2022-06-22 10:18 UTC, Arnei commented on src/redux/themeSlice.tsx
> +  const theme = localStorage.getItem('theme');
Maybe call this `themeId` or something similar, to disambiguate it from the theme objects in cssStyles.tsx.

2022-06-22 21:32 UTC, lkiesow commented
I don't like the really big mode toggle as a first and thus very highlighted option in the main menu. It works completely different than all other buttons by not switching any views, and you will barely ever need this. Maybe we could do something like replacing the keyboard icon with one for additional settings and views (represented e.g. by `···`) and then place the mode toggle and the keyboard settings there.

Also, +1 for smaller icons.

2022-06-23 10:15 UTC, Arnei commented
Correction: I can't seem to find why I thought the buttons where bigger, apparently they aren't. Forget that comment.

2022-06-29 15:04 UTC, Arnei reviewed
* Very small thing in the DateTimePicker Modal: The forward/back arrows in the TimerPicker portion are not greyed out properly in dark mode. But I honestly wouldn't block this PR just because of that.
*Probably not your fault, but the icon on the settings button jumps slightly when hovered

2022-06-30 07:07 UTC, Arnei approved these changes

2022-07-05 08:02 UTC, Arnei requested changes
Just happened to notice that the "Generating waveform" text and loading icon are still black in dark mode and thus very hard to see (they're in the middle of the waveform area).

2022-07-05 08:02 UTC, Arnei commented on src/main/ThemeSwitcher.tsx
> +
Now the code is run on every rerender. Does this need to be run more than once on start-up?

2022-07-05 08:02 UTC, Arnei commented on src/redux/themeSlice.ts
> +    toggleTheme: (state, action: PayloadAction<theme["theme"]>) => {
Still taking a parameter it does not use

2022-07-05 08:10 UTC, Arnei commented on src/main/ThemeSwitcher.tsx
> +  const selectStyle = {
I'd assume you could define a general select style in `cssStyles.tsx`, like for example `basicButtonStyle`.

2022-07-06 07:21 UTC, Arnei approved these changes

2022-07-06 07:22 UTC, merged