High contrast mode for subtitle editor
opencast/opencast-editor pull request #841
Opened 2022-10-21 07:55 UTC by naweidner

- subtitle view now has a working  high contrast mode
- added some new color-attributes (subtitle_segment_bg, subtitle_segment_border and subtitle_segment_text)
- colors for subtitle elements adjusted (bg-color, text-color, border-color etc)

2022-10-28 15:13 UTC, lkiesow requested changes
The high contrast mode lowers the contrast for the subtitle editor's video selector. The label is not legible at all anymore and the border is also no longer visible, making it hard to understand that this is a dropdown menu:

![Screenshot from 2022-10-28 17-02-13](https://user-images.githubusercontent.com/1008395/198669420-da1926fc-dce9-48b2-b1e7-2d80e6b8a136.png)

In high contrast mode, the language selector is literally black on black and you have to mark the text to read it:

![Screenshot from 2022-10-28 16-59-32](https://user-images.githubusercontent.com/1008395/198672530-8ebab6d3-92e8-4a8d-9605-4ddf7de2fd3a.png)


The borders of the segment start and end times run into each other in high contrast mode. There should be at least a bit of margin between these fields:

![Screenshot from 2022-10-28 17-00-45](https://user-images.githubusercontent.com/1008395/198672119-eb630627-6787-46a2-aed1-64dae031c6a8.png)

2022-11-14 09:54 UTC, Arnei requested changes
The issues above all seem to have been addressed. Got one more related to the code.

2022-11-14 09:54 UTC, Arnei commented on src/main/SubtitleVideoArea.tsx
> +  const muiStyle = makeStyles({
This is already defined in SubtitleSelect.tsx. Can we define it in cssStyles.tsx instead to avoid duplication?

2022-11-30 15:38 UTC, Arnei commented
The hint for the dropdowns does not show if the dropdown was in focus once and then isn't anymore. Only in dark-high-contrast mode. Probably because the color matches the background-color.
[Screencast_30.11.2022_16:35:26.webm](https://user-images.githubusercontent.com/14070005/204840970-70ff66b2-4f83-422c-b83a-e93913eafcfa.webm)
(Same for the create dropdown in the select view)

2022-12-01 15:02 UTC, naweidner commented
Last commit didn't fixed the label-issue. Can't reproduce this on localhost (on localhost it looks "normal" for all color modes). 
This is only visible when you use a deploy link.

I also noticed that the clock in the calendar (in the metadata view) looks normal via the deploy link (all color modes) but the colors are not correct via localhost (all color modes).

localhost:
![grafik](https://user-images.githubusercontent.com/93541078/205078262-d5a06f0a-0595-45bb-b59c-151c42d56932.png)

Deploy-Link - https://test.editor.opencast.org/841/2022-12-01_13-50-28/ :
![grafik](https://user-images.githubusercontent.com/93541078/205078508-96ca8276-dcb3-42c4-acf3-101fe3e1474a.png)

2022-12-02 10:01 UTC, Arnei commented
Seems like running the app with `start` or building with `build` results in slightly different css-classes and, more importantly for us, different css-class-*names*. Since we hard-code css-class-names for the MUI elements, using a class name that is only present in one of the builds will result in the rule missing from the other.

It would still be extremely great if we didn't have to rely on hard-coding values for automatically generated class names.

2022-12-09 09:11 UTC, Arnei commented
Somewhat nitpicky, but in regarding the clock view in the calendar: In light high contrast mode, for the arrows to switch between hours and minutes, the contrast is not very high (they are black when you can't click them, and dark blue when you can).

Looks good otherwise. Very happy you managed to get rid of the hard-coded class names.

2022-12-09 14:57 UTC, Arnei approved these changes

2022-12-19 08:35 UTC, merged